---
- name: Ensure hosting folder exists
  become: true
  ansible.builtin.file:
    path: "{{ pxe_path }}"
    state: directory
    mode: "0777"

- name: Copy files to server (this may take a minute)
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/data/files/"
    dest: "{{ pxe_path }}"

- name: Copy iso to server (this may take a minute)
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/data/iso/"
    dest: "{{ pxe_path }}/iso"
