---
- name: Render PXE resources
  hosts: localhost
  roles:
    - role: ../../roles/pxe
      tags: render

- name: Set up TrueNAS as PXE server
  hosts: truenas
  # become: true
  roles:
    - role: ../../roles/truenas
      tags: push
