---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
# https://github.com/PyratLabs/ansible-role-k3s#server-control-plane-configuration

# Define the host as control plane nodes
k3s_control_node: true

# k3s settings for all control-plane nodes
k3s_server:
  node-ip: "{{ ansible_host }}"
  tls-san:
    # kube-vip
    - "{{ kubevip_address }}"
    # # if different from kubevip_address
    # - "{{ k3s_registration_address }}"
  docker: false
  flannel-backend: "vxlan" # "none" # This needs to be in quotes
  disable:
    # - local-storage
    - metrics-server # managed with flux
    - servicelb # use metallb
    - traefik # managed with flux
  # disable-network-policy: true
  # disable-cloud-controller: true
  write-kubeconfig-mode: "644"
  # Network CIDR to use for pod IPs
  cluster-cidr: "10.42.0.0/16"
  # Network CIDR to use for service IPs
  service-cidr: "10.43.0.0/16"
  kubelet-arg:
    - "feature-gates=GracefulNodeShutdown=true"
    - "feature-gates=MixedProtocolLBService=true"
  # Required to use monitor these components with kube-prometheus-stack
  kube-controller-manager-arg:
    - "address=0.0.0.0"
    - "bind-address=0.0.0.0"
  kube-proxy-arg:
    - "metrics-bind-address=0.0.0.0"
  kube-scheduler-arg:
    - "address=0.0.0.0"
    - "bind-address=0.0.0.0"
  etcd-expose-metrics: true
  kube-apiserver-arg:
    - "anonymous-auth=false"
    # - "oidc-issuer-url={{ kubernetes_oidc_issuer }}"
    # - "oidc-client-id={{ kubernetes_oidc_clientid }}"

    # - "oidc-username-claim=email"
    # - "oidc-groups-claim=groups"
  # node-label:
  #   - "node-role.kubernetes.io/master=true"
  node-taint:
    - "node-role.kubernetes.io/master=true:NoSchedule"
