---
- name: Add crowdsec key
  shell: curl -L https://packagecloud.io/crowdsec/crowdsec/gpgkey | sudo apt-key add -

- name: Add crowdsec source
  copy:
    content: |
      deb https://packagecloud.io/crowdsec/crowdsec/ubuntu/ focal main
      deb-src https://packagecloud.io/crowdsec/crowdsec/ubuntu/ focal main
    dest: /etc/apt/sources.list.d/crowdsec_crowdsec.list

- name: Add eternal terminal key
  shell: curl -sS https://mistertea.github.io/debian-et/et.gpg | sudo apt-key add -

- name: Add eternal terminal source
  copy:
    content: |
      deb https://mistertea.github.io/debian-et/debian-source/ bullseye main
    dest: /etc/apt/sources.list.d/eternal_terminal.list

- name: Apt update
  shell: apt update
  become: true

- name: Upgrade all system packages
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_upgrade
  retries: 5
  until: apt_upgrade is success

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ apt_install_packages }}"
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_install_common
  retries: 5
  until: apt_install_common is success
  when:
    - apt_install_packages is defined
    - apt_install_packages is iterable
    - apt_install_packages | length > 0

- name: Install crowdsec packages
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  loop:
    - crowdsec
    - crowdsec-firewall-bouncer-iptables

- name: Install eternal terminal
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  loop:
    - et

- name: Check if Raspberry Pi
  command: grep -q  "Raspberry Pi" /proc/cpuinfo
  ignore_errors: true
  register: is_raspberry

- name: Install raspberry specific packages for Ubuntu 21 or greater
  ansible.builtin.apt:
    name:
      - linux-modules-extra-raspi
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_install_raspberry
  retries: 5
  until: apt_install_raspberry is success
  when: is_raspberry and (ansible_lsb.major_release|int >= 21)

- name: Gather installed packages
  ansible.builtin.package_facts:
    manager: auto

- name: Remove packages
  block:
    - name: Check if snap is installed
      ansible.builtin.debug:
        msg: "snapd is installed"
      register: snapd_check
      when:
        - "'snapd' in apt_remove_packages"
        - "'snapd' in ansible_facts.packages"
    - name: Remove snap packages
      ansible.builtin.command: snap remove {{ item }}
      loop:
        - lxd
        - core18
        - core20
        - snapd
      when:
        - "'snapd' in apt_remove_packages"
        - "'snapd' in ansible_facts.packages"
        - snapd_check.failed is defined
    - name: Remove packages
      ansible.builtin.apt:
        name: "{{ apt_remove_packages }}"
        state: absent
        autoremove: true
    - name: Remove files
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      loop:
        - "/home/{{ ansible_user }}/.snap"
        - "/snap"
        - "/var/snap"
        - "/var/lib/snapd"
        - "/var/cache/snapd"
        - "/usr/lib/snapd"
        - "/etc/cloud"
        - "/var/lib/cloud"
      when:
        - "'snapd' in apt_remove_packages"
        - "'cloud-init' in apt_remove_packages"
  when:
    - apt_remove_packages is defined
    - apt_remove_packages is iterable
    - apt_remove_packages | length > 0
