---
# network ups tools CLIENT configuration

# skip install -- should be handled by packages.yaml tasks
# - name: install nut client
#   package: >
#     name={{nut_client_package}}
#     state=latest

- name: Force systemd to reload itself
  systemd:
    daemon_reload: true

- name: configure upsmon.conf
  template:
    src: upsmon.conf.j2
    dest: "{{ nut_config_path }}/upsmon.conf"
    owner: root
    group: "{{ nut_user }}"
    mode: 0640
  register: upsmon_conf_result

- name: configure nut.conf
  template:
    dest: "{{ nut_config_path }}/nut.conf"
    src: nut.conf.j2
    owner: root
    group: "{{ nut_user }}"
    mode: 0640
  register: nut_conf_result

- name: ensure nut services running & enabled
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - nut-client
    # - nut-driver
    # - nut-server
