---
metal:
  children:
    metal-ctrl:
      hosts:
        datto0:
          ansible_host: 10.2.118.10
          mac: "54:b2:03:70:8b:6c"
          disk: nvme0n1
          network_interface: enp0s31f6
        datto1:
          ansible_host: 10.2.118.11
          mac: "54:b2:03:70:26:03"
          disk: nvme0n1
          network_interface: enp0s31f6
        datto2:
          ansible_host: 10.2.118.12
          mac: "54:b2:03:70:74:03"
          disk: nvme0n1
          network_interface: enp0s31f6
    metal-work:
      hosts:
        datto3:
          ansible_host: 10.2.118.20
          mac: "54:b2:03:71:12:90"
          disk: nvme0n1
          network_interface: enp0s31f6
        datto4:
          ansible_host: 10.2.118.21
          mac: "78:f2:9e:91:77:24"
          disk: nvme0n1
          network_interface: enp0s31f6
        datto5:
          ansible_host: 10.2.118.22
          mac: "78:f2:9e:91:7c:83"
          disk: nvme0n1
          network_interface: enp0s31f6

        # rock1:
        #   ansible_host: 10.2.118.31
        #   mac: "00:e0:4c:88:03:b7"
        #   disk: mmcblk0
        #   network_interface: enp1s0
        # rock2:
        #   ansible_host: 10.2.118.32
        #   mac: "00:e0:4c:88:01:85"
        #   disk: mmcblk0
        #   network_interface: enp1s0
        # rock3:
        #   ansible_host: 10.2.118.33
        #   mac: "00:e0:4c:88:04:23"
        #   disk: mmcblk0
        #   network_interface: enp1s0
        # rock4:
        #   ansible_host: 10.2.118.34
        #   mac: "00:e0:4c:88:04:e0"
        #   disk: mmcblk0
        #   network_interface: enp1s0
        # rock5:
        #   ansible_host: 10.2.118.35
        #   mac: "00:e0:4c:88:04:d3"
        #   disk: mmcblk0
        #   network_interface: enp1s0
        # rock6:
        #   ansible_host: 10.2.118.36
        #   mac: "00:e0:4c:88:05:0a"
        #   disk: mmcblk0
        #   network_interface: enp1s0
        # rock7:
        #   ansible_host: 10.2.118.37
        #   mac: "00:e0:4c:88:04:ff"
        #   disk: mmcblk0
        #   network_interface: enp1s0
        # rock8:
        #   ansible_host: 10.2.118.38
        #   mac: "00:e0:4c:88:01:94"
        #   disk: mmcblk0
        #   network_interface: enp1s0
  # vars:
  #   ansible_user: nrl

nas:
  hosts:
    truenas:
      ansible_host: 10.2.1.1
      ansible_user: root
      pxe_path: "/mnt/slowpool/pxeboot/"

router:
  hosts:
    opnsense:
      ansible_host: 10.0.0.1
      ansible_user: admin
