---
all:
  vars:
    ansible_ssh_port: 22
    ansible_ssh_common_args: -o StrictHostKeyChecking=no

  children:
    kubernetes:
      children:
        controller:
          hosts:
            optiplex0:
            optiplex1:
            optiplex2:
        worker:
          hosts:
            optiplex3:
            optiplex4:
            optiplex5:
    ubuntu:
      children:
        kubernetes:
        terraform:
        other:
    crowdsec:
      children:
        crowdsec_lapi_server:
          hosts:
            opnsense:
        crowdsec_agents:
          children:
            ubuntu:
    infra:
      hosts:
        opnsense:
        truenas:
    other:
