# ---
# terraform:
#   children:
#     tf-ctrl:
#       hosts:
#         k-ctrl-01:
#           ansible_host: 10.2.113.130
#         k-ctrl-02:
#           ansible_host: 10.2.113.131
#         k-ctrl-03:
#            ansible_host: 10.2.113.132
#     tf-work:
#       hosts:
#         k-work-01:
#           ansible_host: 10.2.113.140
#         k-work-02:
#           ansible_host: 10.2.113.141
#         k-work-03:
#           ansible_host: 10.2.113.142

#   vars:
#     network_interface: ens192
