ansible_user: ENC[AES256_GCM,data:Ww8y,iv:j4GdrPV6yRfi3Suyw5kvz3jP8aLY85TpBlMJKWQ20O0=,tag:7b0HB071rg8rg3U9OyxCJw==,type:str]
ssh_authorized_keys:
  - ENC[AES256_GCM,data:+fGvSoeYGNbsXfbp1OT3bU5hQaZS8ufsOztg8f+sYd+KxePX+bfIfGUP0Av3jUTt/KlqNHUDr5sVra3wUspL07gIIvF4qLnKVGhEzx9pFX57B4hix/Y57EJk6ULxvGSOb9f82YSgTvWk9EZFK+4Ku/W5f2sQb9E6ISSp2da8vFhEabVhOewo07Qtva29Z356q5nMusEPrkdQNgKJVybumrXEykxVkWJ6SLCu/tJ61NlGOxZoeEVQlZ7ywQoJEr+I1hSOkfjn4d5IRHCb9jQVJAYs2rS1T3ci8nG2k4vFkyKqJivyXHBlP7QkjDWz5huA6a/nwTQoybNzzAILai78/4DQP5GfhveABFfJ0S+Rq6nRjlIJr4DhzmNWA3q7QLFGCxBvnm0tybtoKSRuhmjUo+4+BiB3QIjN2pV/zXgOYYYoZzBna0lF+nrVv3hzBX4NoHz3ZWXkSBkmwnvpOz3pQ4G11mmDbK2aVwh3hbJi/TRup8F0TqDjvZuNZ7Z2Lp08UBedpOLFNkbrrqCJd9cofdKjR2y2FX0Bwy/5aYJTNEQ4UQDXmtbvF+BBhMKeiFhhJxg7QCvuo6QNTjrADMeYEGfm2cdNy4SFyFnA6uR13wgkRXYfdYFO86PkAOoLxcdHonBpsvaj/n9dFzNU5O3rAGU7XGUwW/com+1yr0aScYJ6Kis5QfRnziivMkvi0V8n7u0suOd4PqGGZ2W3PReQUSdoeLVL131c+uu6+umqF2Zj6KUrqzftJyAT8/LRrwOgtPRnJWqyeNB9jdoVPbhC2Gm9a2cR9hlNd5EPR/06mxGlByaWCNX0IajrbhTOYtO8P0sPGP8m/70dYWuYDj+jE5qSjbkDriCHIBZQNOUN0D8PLVIZRc9Zec7VmNDtxYkmY/aqjK9SvAJ6ztjaGCIEushXcD/q6Vuk7Be5oXLx4A5b3lBujc+dvy3lvZ42cB5Afk9RCGeZlacpbvgFPNk8iZkaverto+LvNeYCMnXF4Q==,iv:6UBvdHehNjQrQ2JEqpLr7mMq7R40XSjqYBc9dQ+YsNM=,tag:seF6uEVCQH9ezbGWQfQFxg==,type:str]
  - ENC[AES256_GCM,data:Im//1u0c/VglOYSqMep+2VFC9FL0h6ZNSXzpnd84fMGb2WMimYH7euD0rKbrqw2tqRJf/I/iF2iD6NotjkSO9yErxTJ+BLi6awVm/ubyuB5FWemP/6XdRkL4WwRg9qG9sQJVqCZOHmxZJqM=,iv:Pzfffr8a6iy9dLmf2O2wVs+7zjSbpNrzwx1GYjQUfPI=,tag:zqkk+3a3PJjdT6qC4yug4Q==,type:str]
email: ENC[AES256_GCM,data:VfFy90H+HWiJYLsMvkZSQ+PlkjY7s+yQ+gU=,iv:d0XCg6euyb/g7hUt238XrZ6bP5PrC3qS3tpopn4DX8c=,tag:BeBlolxgUxe/XyJ6x7ik0A==,type:str]
passwd: ENC[AES256_GCM,data:aftARKFiS2IQor8m,iv:ghSOE7j5Zi06SqfWmEu+OL363qqCW/wrA6XECuTcZyM=,tag:JC7BI+t5TokLvMRQOXN7Ow==,type:str]
crypted_pass: ENC[AES256_GCM,data:1OtClVtnBm4gxfz5/fAuD4k52Zik2xTl8lZF62RejhRe5Pe8kgQYfhl+ro3XzgVhZMR799umOvU9QKTpv3XkLLlEnae/8HyH1cwyGFxl20CuIjV1srpytnNcvc+6MvvHAsdPkVnmFGD98Q==,iv:WTaXbFWoSfDMEZcOO9kBpGhDiFN6AdxnAZI3a4WQH1M=,tag:1G8xdV3Irdcg3J3L6BPF5A==,type:str]
domain: ENC[AES256_GCM,data:bOTIuDoQIP+zyRJHB7wnViM=,iv:zIH7w8jx7u6fad1dScPtVhseRyASRwN9i0nMBJsci/E=,tag:MtUEBSTne9GYnltuFSDMdw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1a7nyvwztvzudynvx92z6tegdxcmudhdh7fh6ty6sqs8n4gh2lelqkqk9aa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcmJrZG91Y1VtSWZCQnJa
        R3B3VjIxb21WZlh5NTJxZ2QxU0hiRVZ0SGhzCk9GTDhsNU1NWWFKanpodXZFV1c0
        dGhDVFh0UEIwSEJnQXlDR3pLV3VmU0EKLS0tIEdoK3MrZmx2Q3BaWllnT2JrRDJU
        YXhWWHFBSEJIZnJJWEFOTFFmQmdsc0EKRrM3ehPXDPGMAQXkdZPf2w60ecdABuh7
        pRkp8QqOer+vlI1UO7YE5uU0Mk6nHX7L2cP6Zp5PrPAnT2x8f9d0Gg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2022-03-24T21:07:28Z"
  mac: ENC[AES256_GCM,data:c/rWOmBj5il63xrCeENZi1jhUQeIdqgNsZj1PM3utyvNY0gt99itg+vXL90/n1V51smlayCMK21HcMLyY8bOZV15TbzgYpG6X6o4caSIdcIgDdAe0oFBZUmMg6XbT2/X89KES2TpHlQiicvg6QXHl1isM8ucLa9CnBeMmNvvAtw=,iv:TfKTLSq9Reo3AoThGzhKvN5gkZU3KtpAcZAApWWIFUk=,tag:illWw2m9jbrLyTX0f22r0Q==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.7.1
