#ENC[AES256_GCM,data:MgHHAwuHqjGXqktnFWORIongo4e4LxXJuDIq4u1Xmae5ig==,iv:bFt1VTBFAkjsWn46c20op1doMKXeOyUYXPbGLwiQtFE=,tag:1rUQiio6cvT5x7yd33LC1g==,type:comment]
timezone: ENC[AES256_GCM,data:PQ7Vafa4a7Sm2Ixpy2u1Zg==,iv:ENnoSUTFk8gmPKxe2xJu5q72Q0P/Zls+8/V+nSuHk1w=,tag:npp5t+dmjEaIkwubtbLfhA==,type:str]
ansible_user: ENC[AES256_GCM,data:R/Vd,iv:eGBUbzf6Bw9ahUuXllBR+x0HzGk12B0XwnMRDKueFtA=,tag:N/OWDKXzDQZwFnZSSE8cPw==,type:str]
email: ENC[AES256_GCM,data:gShVIL2fGB2d5AymBI1eo5Ah2MQIieMIbOo=,iv:U/5fU88PciJS4KIP7XIzer4H/+sDypTaQZW3crdr4c4=,tag:fHymaxPf93YYDQ+1+jLSDQ==,type:str]
default_pass: ENC[AES256_GCM,data:vxRsZbtbYeztdh/S,iv:ThA88EbjkoELGZrwicozanYPXzDOC4GoTcDnNuL7/4o=,tag:VOjHjVfxjIBnwA3uyrnUCg==,type:str]
crypted_pass: ENC[AES256_GCM,data:RpiIsuFtkVDQXsDwCUAotxRLvmQBSNyRrxE9nxcRQJYFhuF+w0OBLLyiy44VMj1O+pHO3/Q1OIMwDF2ogxmV8mEC7a2Fa+F4/VI2YVe7HShTIncn62IwfHESR9aBURPrzMsGA3V+kqxFrQ==,iv:Smch8NXCovRFqO1uwoD3vSqG8tguBvXSyeGaSBAwD+o=,tag:niO9Iv4sX5tOm7vslLV6Iw==,type:str]
domain: ENC[AES256_GCM,data:fd93iYgjWt+rLaN5cvwkRw4=,iv:ZrZd3Eu9rES7Ueyu+kLCGBNupUc/fGqZ1wWgK3dH/Uc=,tag:nsU7Uq5lUD4nt5YBmzvslg==,type:str]
packages:
    - ENC[AES256_GCM,data:6W9N3mlOwv2r+t9r+Cw=,iv:nioaIaHbPZGqp0SkSnKdCLzDey3Mf++7u7DkOJnc7Zs=,tag:jyDUPBGYhIz1tcnIhRqGPA==,type:str]
    - ENC[AES256_GCM,data:Pw91IvYPZj16dk0KVPAnU43LwQ==,iv:VzKkQOyqMAIfv+j0O8RoWbEnrdk4r6NiAGNf8m6jsM4=,tag:mQGaVdIfzkR4neQUgW3pLw==,type:str]
    - ENC[AES256_GCM,data:OpnzTkoOkwzE,iv:eD2hiQ/nwT0UNrqyo3npSPx9FXamWau05SldpRt76Eg=,tag:Vw0XnXvcZaHfEGvY/0iWYg==,type:str]
    - ENC[AES256_GCM,data:bMogCQO4Rvk00Py3743f,iv:VxYkY7XDleYQoBejIurfFu0+pyKXXiaq12YqDyfQt44=,tag:jHQksZ2zr1QG/+WETiaMkg==,type:str]
    - ENC[AES256_GCM,data:P1HFcUId3RyliA==,iv:wdcTByVqwtGcDEuJuvZiCyUevy0tV2cW23xHv5Gq1HE=,tag:dk8sVQl678lXTjjBcJYkGw==,type:str]
    - ENC[AES256_GCM,data:wL79CQ==,iv:MPDt0czB4KscDVKRCh4BHG3Plig6+jijRdgE9Jc2w+4=,tag:lwZq3B7IMPCVs43/+yl5Og==,type:str]
    - ENC[AES256_GCM,data:Ma23pqZFafM=,iv:o7Sbji/AsizZOh0BPSmQTrHNr9qA8FVNq6g2K8zOsLs=,tag:zTAwsgusqSQR6WFqmFJZyg==,type:str]
    - ENC[AES256_GCM,data:IHtswiI=,iv:5zM9QgnKK+1DjPqEuH7hxPptzUHCLxG5/09uv46LSwU=,tag:CHC5ezQm/HCTyW4fZXdDQQ==,type:str]
    - ENC[AES256_GCM,data:yAOevr0=,iv:GCDnomKGIUbd4mfDarp3UGSIwALdTKJxo3RHYBcDXuY=,tag:4oTc+mgiuOPjJU84gzMvvA==,type:str]
    - ENC[AES256_GCM,data:6Sk0O/Ma,iv:OUGiXqGn0Ruv41DzW1VYKRaSw6T7K4zsrSYEi83Y5IQ=,tag:vBb/1v+1YIEGYtHv2SYVRQ==,type:str]
    - ENC[AES256_GCM,data:55d+2g==,iv:lrTIb/5q/AWhOcnI3ypZIOxriweFCMHylp4+LfezVnI=,tag:Qqqkwkq1nI4rxOA6r+QxoA==,type:str]
    - ENC[AES256_GCM,data:GwHIb/scE2QSigWL,iv:U3oVgQDeBsXj3xZ9Wl0rSusZyfH/HVwX21inQQT5TiM=,tag:NjPY6T+W75AOl+8KE/Fwfg==,type:str]
    - ENC[AES256_GCM,data:IA4R7LphsyjJHqjAvGAu,iv:zAcfq4q8VSL9+fReeRLaNCJrszKgEgVcF1TSfSbpdug=,tag:0Ywl7UK3E0F22gbaXEFNjw==,type:str]
    - ENC[AES256_GCM,data:AwyGQGzJjQ==,iv:6H/OZUQkyoVD1a3KiezY4nuDE2Xn+g1KOUdG6gCyJfI=,tag:tSD1jvBwB8CftUXo146kZw==,type:str]
    - ENC[AES256_GCM,data:XWuUhLD9AY/XxQ==,iv:KX72qb4umvBOVlSEkSxqJEPt38iV8qdjO8bjmWzy6IM=,tag:GT+cVBhaHiitY+WM0tjQ0A==,type:str]
    - ENC[AES256_GCM,data:LSezNp+0,iv:cUxVVU8f0npXIPz8OsK1kTh9yPapgiQ/ECaYpSY+MDc=,tag:ZPjaRbCxbQ7X4U22+tCm+g==,type:str]
    - ENC[AES256_GCM,data:mAxRwQ==,iv:1+fmW3mnt4mVASi1kvHFLD2nb4VUNpbG2FfyB+h6QZM=,tag:wqOVUUL88zKWbf3U6z6RZw==,type:str]
    - ENC[AES256_GCM,data:UGaXIYquuoqPL0YWJ8PJ,iv:H+NwFyCKX/daXPcHmH4oDfbaQdVB2g7uRGxbJO68m+E=,tag:1Yht9TK+sB4tK1vPqm5YYA==,type:str]
    - ENC[AES256_GCM,data:6xeVqg==,iv:6e6lRKm0RyXvOf0P2FKkQyVnLKDgNJqm/td89/O+JaM=,tag:CMZk2OGQKC4nU06yIo5kgA==,type:str]
    - ENC[AES256_GCM,data:eZMlgHUBQtT2,iv:csgQX4F461dotWaAobsmBOKenm5b3hQv136SnHZyVqs=,tag:ZC6Qw0Uju7ynSyOuURm52Q==,type:str]
    - ENC[AES256_GCM,data:Y9/IRRIaptZkCA==,iv:4f/Luwl2KP6QBh0fCSa9hn4em8sgc+Yzlq4ePdbU/38=,tag:S1j9xqFfuZ3OJmkbBzm9Rg==,type:str]
    - ENC[AES256_GCM,data:BTqxKB1uEw==,iv:xCno1NfuxvPvIygrbB1zR461NaKWRohvQ9H8t8aDyPs=,tag:qSwH9+TRr8j1wy9xq08ChA==,type:str]
    - ENC[AES256_GCM,data:rtmehNSNlJyzCQ==,iv:/cHRvD4V32SqSBqEek/NDY5RhuD6+CTPQkvqe/BG9ok=,tag:dkD5lf1ti1CB0qAS1wL7Wg==,type:str]
    - ENC[AES256_GCM,data:qV8AVnCLR0o=,iv:UU2MC+LKCc3xGxRVwo0ppfsnp1Fpd9XFnF6HYMobsTo=,tag:UE1p0xHrEwoKQRKD8cz0Ww==,type:str]
    - ENC[AES256_GCM,data:qv20lyXPyOzw9g==,iv:+QThqQiWEGZm8Z2cYo4Fb6s35ch4TeTTqbQ/5OTfQhM=,tag:fIYV2E9jbgjKqLjMuyLVmA==,type:str]
    - ENC[AES256_GCM,data:LHMIQu6K,iv:+5fBcxLt+DXFx1aBqn8kY89JSO+kWi39lByji6lsuho=,tag:J0wkTp6LC7Y/0l5JljXFfg==,type:str]
    - ENC[AES256_GCM,data:EVTv9a2bPC4xy+vqzTzFv2o=,iv:Ho5dPt13fQWHsOG9/N0ahkgx8L7khE1m7SG7jo5KsNE=,tag:h5GApAbg3FHq4pOW8kjQvw==,type:str]
    - ENC[AES256_GCM,data:1jYqNXiOBw==,iv:mY2/0dAIye5hv9vZZ7dQ67YemwmNOHoWQwG3Yj1yKNM=,tag:VFpcMBzwtlrIRkSBreRKmQ==,type:str]
    - ENC[AES256_GCM,data:DYpBbeyUyR7n5O8fXgSKNcQk,iv:X4NFDqwK9ScFckeZ63jRfU73UkMIbNvgFAQylk2JNXI=,tag:Ylu5TNJmTJZy6zj87LxiNg==,type:str]
    - ENC[AES256_GCM,data:jb+lHyZJ83cGWRHb,iv:eHCEwgT+5Y/3gvjgdLxfAdXOkZHrfZ12USf7lryRUmY=,tag:8ygcvDAZ82+8rD89il8+sQ==,type:str]
    - ENC[AES256_GCM,data:+EBipCIj0Xf3,iv:pw6QiJnjvt1Q9Jhp5XhFAtNUKu5SwIhJcDU8AHHMNVk=,tag:kQk+HAHCBD8bK6dlxx4DwQ==,type:str]
    - ENC[AES256_GCM,data:rOP4jR+wdjNu,iv:1ATwwu5mqOgS3mr37y5OLGOaYCZvF9F5bR6cc9DVjZQ=,tag:zxLzghwr3mP6WohIDJgtTw==,type:str]
    - ENC[AES256_GCM,data:QjOjrp4vz49SjFIo9w==,iv:5A3zfjCxCzaFDkgBAqVISFWe90ozhoofxMBZwewTBoE=,tag:XY2xj5cRKI1J6vVnPKR79w==,type:str]
    - ENC[AES256_GCM,data:AujusUI=,iv:VL+pKdlu4Gw0qELBumL67JgOgTl4pACXFzALkT5isOY=,tag:o7hIyHCoUItE8uVDvw+3QQ==,type:str]
    - ENC[AES256_GCM,data:h/mdgcxtICKxJ3ULWVQKHDD4hOBj1sb0mt4=,iv:sMZKpVOEHp7MfGCnUvPKHSUde3jEhQKatolYFugTkr0=,tag:NWUaE9g1GwQujqSoi6IxeA==,type:str]
    - ENC[AES256_GCM,data:UNnFWBJxBHD4u6pqVpmk6wBw3w==,iv:HUC/ejJ2Szsnd9K3blmvzGTDMt7sQTeZMTydwZaxFSc=,tag:fyQTABgDtyfsvre3nRjJHg==,type:str]
    - ENC[AES256_GCM,data:5svh6ZM=,iv:VBuYzklj/MFz9PPQsoWSYU5o79EHSJN05WlIZydpBaQ=,tag:Zft0/58mPo4cR06F8IXz4A==,type:str]
packages_remove:
    - ENC[AES256_GCM,data:SYQW9XLuY/vxhD4=,iv:rzclXjHZU5agb/MUjcS8Mtnqx1Lfh4ZWQB8HdpCjxXA=,tag:/vk/KVeh36J8hvTLqV04lA==,type:comment]
    - ENC[AES256_GCM,data:ZbA4Zo1v,iv:bvVvIOLt7Enq6FNDq7pAIdskZ80nnb6ezWVqc1GNQP0=,tag:IeTkKNJmqkFZ7WSjplTCjQ==,type:str]
    - ENC[AES256_GCM,data:CJUWZymPg6wNr5TO,iv:Gk+0airK3ydpcxug7GzKsLJrAa4GiV09hpEQgYUW6Bg=,tag:adFbKllBQwFk0j4Zm7PCNA==,type:str]
    - ENC[AES256_GCM,data:G1y9QZrVztOWyXU=,iv:JhdLyN3ZfzhvgMlcVv+nGmBWjf+BmC3KjefDQCCJ0Fw=,tag:k6RN9PvbMifJDxg2Z7kihw==,type:str]
    - ENC[AES256_GCM,data:14RpPds=,iv:TcbgA7Orbt8qLR71Hy+MTtMzCSw1TSQ+GfrFOgXKn4c=,tag:n/23DGagGGaVnpxbfc7M6g==,type:str]
    - ENC[AES256_GCM,data:ZI2N75zkflbMCA==,iv:GGQ8LmYuFWUIKH1rr/dQIhgzuyhrorH/Wh5UYMhPClI=,tag:GTlJjS9Qrw2QGzHH3cye5A==,type:str]
    - ENC[AES256_GCM,data:M4JfYk3x25Ar4wWgSnjNYmw=,iv:SuC5wOhEZ3LEMrcJIQKEGtKy3hI7DAKPPVd1l9Sn0pU=,tag:VJIKp8BuF4IqJyydkbP3Hg==,type:str]
    - ENC[AES256_GCM,data:FNaVNgGV8dJ+nQE4eztt8pGwnSGTb+V4,iv:j5h2kH6Hl5a26py4ByYpBi+XQn3Inco8O0q3G3SJiUo=,tag:i/4ERi6Qv63v6Dut987tXQ==,type:str]
    - ENC[AES256_GCM,data:Bje41XlbSAGNslhTHXBH2zTgPA8Il4nOO7nF,iv:JkREMTfDwCrbINJ4bhHkzQF6lK0dXnF4a+hCsjvV6TM=,tag:z2Xb5gjGwfyeiglvoHAXSg==,type:str]
    - ENC[AES256_GCM,data:zibhs8rK2TJ1rTMVZxQF5W8=,iv:RXgA4hF3aqh5G7UksbUaks6avjauNWvAOh4AvZk/Ee8=,tag:0Q+PqHlSWI9DkNgP4vUAFg==,type:str]
    - ENC[AES256_GCM,data:8F9g3RI=,iv:9lLEFY97ZJcTsEcdkkcB540eQ0DNFNz4a2vmU+zg7/w=,tag:HDHqHGIbAx+BKkBpLx6EKw==,type:str]
    - ENC[AES256_GCM,data:1wlMsgKJxrK42notBCCZ5Q==,iv:Xuuzz5kPz4E1gztV6cf1gfaE36IGR0i/p3XFZUGx4pg=,tag:S6X96jFmPxa/63cPUZ8UdQ==,type:str]
    - ENC[AES256_GCM,data:4TY8dMmIK2jMI7fEjIbiUQ==,iv:MRdpAvy/AlyRf95X38dBHqqy4R88H8Px+ZLN9CtfEeA=,tag:DtMrIdav1GZ0TULAcWGFKg==,type:str]
    - ENC[AES256_GCM,data:encM5mTZJg==,iv:uK8x8RUPcri07EjXkyigX4Rs5luBAPrEf8Zzp1JGJZY=,tag:k830ZYfOSykcaj93jpH+rA==,type:str]
    - ENC[AES256_GCM,data:R3U9G8ALWXo1XlXO5w==,iv:pljZofvMM450O7ZJt5S5YC5a/nv7YxIBZn+HlMpLVRk=,tag:Y+aCRKu7vTHf8/n1JsCnMw==,type:str]
    - ENC[AES256_GCM,data:Vh00qmWFJBA=,iv:4gN1Arl0xakRdLxX24l3huDU7GwCuv2Td1m9EN5LJ3c=,tag:a67qFCiFzxy5awPRxa63fw==,type:str]
    - ENC[AES256_GCM,data:nw3FxsYhMS+446I1fQc8IdO/0QTjl6UK0Z0=,iv:SxrGT7wDn3BR59U5eBkAdP7rU6LVwBJHiC6DaeL0Qqg=,tag:ZN11w4JbqU6VU1hdgZgLeA==,type:str]
    - ENC[AES256_GCM,data:gtWrFAp5pX4+r2sseCNx0p5c,iv:LUzYTsND9pZkItRkKJbz3ubG0mT2INLgY3UYqrdthf0=,tag:61idb1mXCyT/WofOH8353Q==,type:str]
    - ENC[AES256_GCM,data:zyht/+4=,iv:suI2tHWhLkTHwgg8Fc9vAL3bUaGUoyATKy0zUTsNRfM=,tag:9ZAijF6CG3BFMjevokWImQ==,type:str]
    - ENC[AES256_GCM,data:xR/rgVS6yeub,iv:xPIFwJHFGf1RItfdbCpscWp/WN3ZA7O1yhcM3FKBqIE=,tag:2X9rT++US3CRbYOMshYiVg==,type:str]
    - ENC[AES256_GCM,data:jDtBNA==,iv:RDunpJinee9TSggVl4i5kEcpqFKi71DfduE/Omg0Q4Q=,tag:GPAhVn2aajas4mqVXdzo8A==,type:str]
    - ENC[AES256_GCM,data:BNJcKvqBm5EoLwzljqZSvH/Z1zesug==,iv:RS4NepTH3xUyXDtEY678x6XUXgkZKLtaWhKK0QJ2/f8=,tag:d6RpanBzRfivJR/MR8YMkg==,type:str]
    - ENC[AES256_GCM,data:O8ep4Or5,iv:aA7DSwtZlVJRTPbxTisRhd8A4NDf1/88WRFGMKNLPDU=,tag:7J66qE/hM19uinz0Lw3l0g==,type:comment]
nut:
    nut_config_path: ENC[AES256_GCM,data:Qv8gpVCjp3I=,iv:mD3IT+F98rlmUfeTFP4TZNzvGnIsXj4HQoMYYcpRns4=,tag:sf2Do1kxTKI1RT4Gidk7dg==,type:str]
    nut_user: ENC[AES256_GCM,data:G11Y,iv:MT3ac+p4y17a3ys6iC9rkt0NhyOUn92Jvl7ERTeVPHI=,tag:EzRw5A3yK3XUBlUccpdRaQ==,type:str]
    nut_mode: ENC[AES256_GCM,data:1uY1/oq6anVE,iv:c1c9iYwZ+pTPwiXPIcB+YfldI/HfJMlIvkL9ocigiKk=,tag:h1Wa/qENY1wbK2wEQI7vAA==,type:str]
    ups_name: ENC[AES256_GCM,data:oiKxEuz3/+Sgew==,iv:gg5h3lIHrJLA3tLJ/Sdfo089A/zNUkyoNm2OuT24tiE=,tag:qI5SoyeEB7soiXDJ+whhyg==,type:str]
    nut_server_host: ENC[AES256_GCM,data:SV1I48I3y7I=,iv:NKs/4y7rCxy1IHvDmyh/82lMtRMs2VlqXtfeC1luElY=,tag:YgGwABWCiPKIVqrRK3Z3SQ==,type:str]
    nut_monitor_user: ENC[AES256_GCM,data:S8/Bk/qX9Q==,iv:QDP/DnavbWQUPjpDFk5c8AM+pFcKvHLxE2rygabH0RY=,tag:9BVZJkgGuIWsLgstc6HiJg==,type:str]
    #ENC[AES256_GCM,data:uOJ8m1DhzGNpcSqSumbPnOpZ8A==,iv:0KdE98lCn9rtUtY5yl2BWfl4yMmbjCgLpYPdJFD+O74=,tag:5WHNgp7nXjmFLa1v4exlfA==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a7nyvwztvzudynvx92z6tegdxcmudhdh7fh6ty6sqs8n4gh2lelqkqk9aa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSUlDRUt1NkdNWG5LTnpM
            TDlDNkZUTHU0QzFHRUk4ZXlSWUQzVytrY0ZRCndrajE0VUlwM0dwV0NvYXNKTlBq
            L0d0Wm5xVnBxMWtham5XYkhnQUtWTEUKLS0tIFdLdjUrSUZvK2ZEandZcFBuQ21H
            MnM5blcrTTZKSllFaGF5aDJSb3o3dWsKrEhqMmEjk/4shgVbuBnr1gZ/0RrJo5vD
            QcX3EzrmiHy6KG9vSCTIiRNu8q9RTWV9adIkL4DhEsBlytDKcsipTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-12T15:50:01Z"
    mac: ENC[AES256_GCM,data:eBppEssxZdWY/wrJ9kjyz4rc8/WE5edNfcSCbvsZhlh8IzOuOQD+PWML2hn7AvrelSljD7LQA2vCCokm1A1aPTm+ehBevEaVKFFGHIIwVkjIXGwr9aNjh2EnvJw2ELBaXN7BYQItpeNezqfvMqvFcVCPj1G49GMRrD/ruEmwIgg=,iv:dumUV2caBkEOnITru+i9ZyCdVX+xesl/3N9apcyKBmc=,tag:0DVk2yHPAGqZydmWxIOAXA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
