### PXE setup
- name: Ensure tftp folder exists
  become: true
  file:
    path: /usr/local/tftp
    state: directory
    mode: "0777"

- name: copy files to OPNsense (this may take a minute)
  copy:
    src: "{{ playbook_dir }}/data/files/"
    dest: /usr/local/tftp/

# i have no idea where to put grub.cfg so it gets read
- name: copy grub.cfg to OPNsense
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "{{ playbook_dir }}/data/files/grub.cfg", dest: /usr/local/tftp/ }
    # - { src: "{{ playbook_dir }}/data/files/grub.cfg", dest: /usr/local/tftp/grub/ }
    # - { src: "{{ playbook_dir }}/data/files/grub.cfg", dest: /usr/local/tftp/boot/grub/ }
    # - { src: "{{ playbook_dir }}/data/files/grub.cfg", dest: /usr/local/tftp/EFI/ubuntu/ }
