---
#
# Below vars are for the xanmanning.k3s role
# ...see https://github.com/PyratLabs/ansible-role-k3s#globalcluster-variables
#

# Use a specific version of k3s
# for latest 'stable': https://update.k3s.io/v1-release/channels/stable
k3s_release_version: "v1.23.4+k3s1"

# Install using hard links rather than symbolic links.
# ...if you are using the system-upgrade-controller you will need to use hard links rather than symbolic links as the controller will not be able to follow symbolic links.
k3s_install_hard_links: true

# Escalate user privileges for all tasks.
k3s_become_for_all: true
k3s_become: true

# Enable debugging
k3s_debug: false

# Enabled embedded etcd
k3s_etcd_datastore: true

# (bool) Allow the use of unsupported configurations in k3s
k3s_use_unsupported_config: false

# Control Plane registration address
# If you want to use kube-vip only set this to "{{ kubevip_address }}"
k3s_registration_address: "{{ kubevip_address }}"

# (list) A list of URLs to deploy on the primary control plane. Read notes below.
k3s_server_manifests_urls:
  - url: https://docs.projectcalico.org/archive/v3.21/manifests/tigera-operator.yaml
    filename: tigera-operator.yaml
  - url: https://kube-vip.io/manifests/rbac.yaml
    filename: kube-vip-rbac.yaml

# (list) A flat list of templates to deploy on the primary control plane
# /var/lib/rancher/k3s/server/manifests
k3s_server_manifests_templates:
  - "calico-installation.yaml.j2"
  - "kube-vip-daemonset.yaml.j2"
  # - "kube-vip-cloud-controller-configmap.yaml.j2" # to replace metallb
