---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/
# https://github.com/PyratLabs/ansible-role-k3s

# (bool) Specify if a host (or host group) are part of the control plane
k3s_control_node: false

# (dict) k3s settings for all worker nodes
k3s_agent:
  node-ip: "{{ ansible_host }}"
  kubelet-arg:
    - "feature-gates=GracefulNodeShutdown=true" # Enables the kubelet to gracefully evict pods during a node shutdown
    - "feature-gates=MixedProtocolLBService=true" # Allow k8s services to contain TCP and UDP on the same port
    # https://github.com/k3s-io/k3s/issues/1264
    - "node-status-update-frequency=4s"
  node-label:
    - "node-role.kubernetes.io/worker=true"
