#cloud-config
# Overwrite default user config
users:
  - default #Define a default user
  - name: ${username}
    groups: sudo, wheel
    lock-passwd: false
    passwd: ${password}
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${ssh_pubkey}

write_files:
  # - path: /usr/local/bin/cleanup-cloud-init.sh
  #   content: |
  #     #!/bin/bash

  #     rm -fr /var/lib/cloud/instances/
  #     rm -fr /var/lib/cloud/instance
  #     rm -f /etc/machine-id /var/lib/dbus/machine-id
  #     truncate -s 0 /etc/machine-id
  #     ln -s /etc/machine-id /var/lib/dbus/machine-id

  - path: /usr/local/bin/iscsi-init.sh
    content: |
      #!/bin/bash

      # Enable multipathing
      sudo tee /etc/multipath.conf <<-'EOF'
      defaults {
          user_friendly_names yes
          find_multipaths yes
      }
      EOF

      sudo systemctl enable multipath-tools.service
      sudo service multipath-tools restart

      # Ensure that open-iscsi and multipath-tools are enabled and running
      sudo systemctl status multipath-tools
      sudo systemctl enable open-iscsi.service
      sudo service open-iscsi start
      sudo systemctl status open-iscsi

runcmd:
  - bash /usr/local/bin/iscsi-init.sh
  # ### Turn off Swap on the OS & persist by removing swapoff from the filesystem mounts
  # - swapoff --all
  # - sed -ri '/\sswap\s/s/^#?/#/' /etc/fstab
  ### Allow IPv4/6 bridge traffic to traverse iptables (required by most CNIs)
  - sysctl net.bridge.bridge-nf-call-iptables=1
  - sysctl net.bridge.bridge-nf-call-ip6tables=1
  # ### Enable vSphere customization to with cloud-init
  # - 'echo "disable_vmware_customization: false" >> /etc/cloud/cloud.cfg'
  # ### remove comment to disable cloud-init; uncomment to enable
  # - 'echo "network: {config: disabled}" >> /etc/cloud/cloud.cfg.d/99-custom-networking.cfg'
  # ### Don’t clear /tmp on reboot for vsphere customisation
  # - sed -i 's/D \/tmp 1777 root root -/#D \/tmp 1777 root root -/g' /usr/lib/tmpfiles.d/tmp.conf
  # ### Clear the machine-id to ensure the cloned VMs get unique IDs and IP addresses.
  # - echo -n > /etc/machine-id
  # ### do we want to clean cloud-init?
  # - bash /usr/local/bin/cleanup-cloud-init.sh

timezone: "America/New_York"
ntp:
  enabled: true
  servers:
    - ${ntp}

package_update: true
package_upgrade: true
packages:
  - acl
  - apt-transport-https
  - at
  - bzip2
  - curl
  - debconf
  - debconf-i18n
  - git
  - gnupg
  - gzip
  - htop
  - iproute2
  - lsscsi
  - multipath-tools
  - open-iscsi
  - passwd
  - python
  - python3-apt
  - python3-pip
  - nfs-common
  - nmap
  - rsync
  - scsitools
  - sg3-utils
  - sudo
  - tar
  - tmux
  - traceroute
  - tree
  - unzip
  - vim
  - wget
  - xz-utils
# final_message: "The system is prepped"
# power_state:
#   timeout: 30
#   mode: reboot
