---
apt_install_packages:
  - apparmor-utils
  - apt-transport-https
  - arptables
  - ca-certificates
  - curl
  - ebtables
  - gdisk
  - hdparm
  - htop
  - iputils-ping
  - ipvsadm
  - lvm2
  - net-tools
  - nfs-common
  - nano
  - ntpdate
  - nut
  - nvme-cli
  - open-iscsi
  - psmisc
  - smartmontools
  - socat
  - software-properties-common
  - unattended-upgrades
  - unzip

apt_remove_packages:
  # - apparmor
  - apport
  - bcache-tools
  - btrfs-progs
  - byobu
  - cloud-init
  - cloud-guest-utils
  - cloud-initramfs-copymods
  - cloud-initramfs-dyn-netconf
  - friendly-recovery
  - fwupd
  - landscape-common
  - lxd-agent-loader
  - ntfs-3g
  - open-vm-tools
  - plymouth
  - plymouth-theme-ubuntu-text
  - popularity-contest
  - snapd
  - sosreport
  - tmux
  - ubuntu-advantage-tools
  - ufw

nut_config_path: /etc/nut
nut_user: nut
nut_mode: netclient
ups_name: PR1500RT2U
nut_server_host: 10.2.0.1
nut_monitor_user: monuser
# nut_monitor_pass: # assumes password in ubuntu SOPS secret
