---
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.3.0
collections:
  - name: ansible.posix
    version: 1.4.0
  - name: ansible.utils
    version: 2.8.0
  - name: community.docker
    version: 3.2.0
  - name: community.general
    version: 6.1.0
  - name: community.sops
    version: 1.5.0
  - name: kubernetes.core
    version: 2.3.2
