---
- hosts: all
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Verify
      pause:
        prompt: This will reboot all specified hosts.  Please confirm (yes/no)
      register: confirm_reboot

    - name: Confirm
      delegate_to: localhost
      run_once: true
      assert:
        that: confirm_reboot.user_input | bool
        fail_msg: Exiting at user request ...
        success_msg: Continuing with reboot ...

  tasks:
    - name: reboot
      reboot:
