---
- name: Reboot
  hosts: all
  become: true
  gather_facts: true
  any_errors_fatal: true
  vars_prompt:
    - name: reboot
      prompt: |-
        Are you sure you want to reboot (yes/no)?
      default: "n"
      private: false
  pre_tasks:
    - name: Check for confirmation
      ansible.builtin.fail:
        msg: Exiting at user request ...
      when: reboot != 'yes'

    - name: Continuing with reboot ...
      ansible.builtin.pause:
        seconds: 5
    - name: Wait for availability
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300

  tasks:
    - name: Reboot
      ansible.builtin.reboot:
        reboot_timeout: 900
