---
- hosts:
    - controller
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5

    - name: Wait for availability
      wait_for_connection:
        delay: 30
        timeout: 300

  roles:
    - ubuntu
