all:
  children:
    masters:
      hosts:
        datto0:
          {
            ansible_host: 10.2.118.10,
            mac: "54:b2:03:70:8b:6c",
            disk: nvme0n1,
            network_interface: enp0s31f6,
          }
        datto1:
          {
            ansible_host: 10.2.118.11,
            mac: "54:b2:03:70:26:03",
            disk: nvme0n1,
            network_interface: enp0s31f6,
          }
        datto2:
          {
            ansible_host: 10.2.118.12,
            mac: "54:b2:03:70:74:03",
            disk: nvme0n1,
            network_interface: enp0s31f6,
          }

    workers:
      hosts:
        datto3:
          {
            ansible_host: 10.2.118.20,
            mac: "54:b2:03:71:12:90",
            disk: nvme0n1,
            network_interface: enp0s31f6,
          }
        datto4:
          {
            ansible_host: 10.2.118.21,
            mac: "78:f2:9e:91:77:24",
            disk: nvme0n1,
            network_interface: enp0s31f6,
          }
        datto5:
          {
            ansible_host: 10.2.118.22,
            mac: "78:f2:9e:91:7c:83",
            disk: nvme0n1,
            network_interface: enp0s31f6,
          }

    nas:
      hosts:
        truenas:
          ansible_host: 10.2.1.1
          ansible_user: root
          pxe_path: "/mnt/slowpool/pxeboot/"

    router:
      hosts:
        opnsense:
          ansible_host: 10.0.0.1
          ansible_user: admin
